package fr.m2.archi.et.model.thrift;

/**
 * Autogenerated by Thrift Compiler (0.16.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.16.0)", date = "2023-12-08")
public class InternalLeadDto implements org.apache.thrift.TBase<InternalLeadDto, InternalLeadDto._Fields>, java.io.Serializable, Cloneable, Comparable<InternalLeadDto> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("InternalLeadDto");

  private static final org.apache.thrift.protocol.TField INFORMATIONS_FIELD_DESC = new org.apache.thrift.protocol.TField("informations", org.apache.thrift.protocol.TType.STRUCT, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new InternalLeadDtoStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new InternalLeadDtoTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable ModelITO informations; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    INFORMATIONS((short)1, "informations");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // INFORMATIONS
          return INFORMATIONS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.INFORMATIONS, new org.apache.thrift.meta_data.FieldMetaData("informations", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ModelITO.class)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(InternalLeadDto.class, metaDataMap);
  }

  public InternalLeadDto() {
  }

  public InternalLeadDto(
    ModelITO informations)
  {
    this();
    this.informations = informations;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public InternalLeadDto(InternalLeadDto other) {
    if (other.isSetInformations()) {
      this.informations = new ModelITO(other.informations);
    }
  }

  public InternalLeadDto deepCopy() {
    return new InternalLeadDto(this);
  }

  @Override
  public void clear() {
    this.informations = null;
  }

  @org.apache.thrift.annotation.Nullable
  public ModelITO getInformations() {
    return this.informations;
  }

  public InternalLeadDto setInformations(@org.apache.thrift.annotation.Nullable ModelITO informations) {
    this.informations = informations;
    return this;
  }

  public void unsetInformations() {
    this.informations = null;
  }

  /** Returns true if field informations is set (has been assigned a value) and false otherwise */
  public boolean isSetInformations() {
    return this.informations != null;
  }

  public void setInformationsIsSet(boolean value) {
    if (!value) {
      this.informations = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case INFORMATIONS:
      if (value == null) {
        unsetInformations();
      } else {
        setInformations((ModelITO)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case INFORMATIONS:
      return getInformations();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case INFORMATIONS:
      return isSetInformations();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof InternalLeadDto)
      return this.equals((InternalLeadDto)that);
    return false;
  }

  public boolean equals(InternalLeadDto that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_informations = true && this.isSetInformations();
    boolean that_present_informations = true && that.isSetInformations();
    if (this_present_informations || that_present_informations) {
      if (!(this_present_informations && that_present_informations))
        return false;
      if (!this.informations.equals(that.informations))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetInformations()) ? 131071 : 524287);
    if (isSetInformations())
      hashCode = hashCode * 8191 + informations.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(InternalLeadDto other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetInformations(), other.isSetInformations());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetInformations()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.informations, other.informations);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("InternalLeadDto(");
    boolean first = true;

    sb.append("informations:");
    if (this.informations == null) {
      sb.append("null");
    } else {
      sb.append(this.informations);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (informations != null) {
      informations.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class InternalLeadDtoStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public InternalLeadDtoStandardScheme getScheme() {
      return new InternalLeadDtoStandardScheme();
    }
  }

  private static class InternalLeadDtoStandardScheme extends org.apache.thrift.scheme.StandardScheme<InternalLeadDto> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, InternalLeadDto struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // INFORMATIONS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.informations = new ModelITO();
              struct.informations.read(iprot);
              struct.setInformationsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, InternalLeadDto struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.informations != null) {
        oprot.writeFieldBegin(INFORMATIONS_FIELD_DESC);
        struct.informations.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class InternalLeadDtoTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public InternalLeadDtoTupleScheme getScheme() {
      return new InternalLeadDtoTupleScheme();
    }
  }

  private static class InternalLeadDtoTupleScheme extends org.apache.thrift.scheme.TupleScheme<InternalLeadDto> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, InternalLeadDto struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetInformations()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetInformations()) {
        struct.informations.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, InternalLeadDto struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.informations = new ModelITO();
        struct.informations.read(iprot);
        struct.setInformationsIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

